### PR TITLE
Create python-app.yml

### PR DESCRIPTION
**Pull request by alligalli**
added steps to test

Will it work? 🐧

### CODE REVIEW

**Review by yauh-ask — DISMISSED** [review]
I see only one job of building so far, no testing. Is that the thing?

**Comment by alligalli** [comment]
> 
> 
> I see only one job of building so far, no testing. Is that the thing?

if you inspect closely the job running in the actions tab you can see there is a test step among the others

**Comment by alligalli** [comment]
i wonder why only 6 test files out of 21 are failing, maybe it has something to do with a missing environment variable?
immagine

**Comment by yauh-ask** [comment]
python -m unittest discover tests
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/2.7.18/x64
......EE..E...EE.E... 

Env-var for python? Compatibility issue?

**Comment by alligalli** [comment]
> 
> 
> python -m unittest discover tests
> shell: /bin/bash -e {0}
> env:
> pythonLocation: /opt/hostedtoolcache/Python/2.7.18/x64
> ......EE..E...EE.E...
> 
> Env-var for python? Compatibility issue?

the environment has python 2.7 installed according to the proposed file, the dependencies are installed, the program itself in installed and the command to run the tests inside the /tests folder works too.
maybe there is a reason why only those 6 tests aren't passing.
could it be something related to the api key not being loaded properly in the environment?
how can we load environment variables in an action file?

**Review by alligalli — COMMENTED** [review]
nothing changed but ok :D

**Comment by alligalli** [comment]
i think this may help, maybe thats what we are missing!

[Using variables and secrets in a workflow](https://docs.github.com/en/actions/configuring-and-managing-workflows/using-variables-and-secrets-in-a-workflow)

**Comment by yauh-ask** [comment]
> environment variables in an action file

env:
      SOCCER_CLI_API_TOKEN: {secret} 

or  

with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

**Comment by alligalli** [comment]
> 
> 
> > environment variables in an action file
> 
> env:
> SOCCER_CLI_API_TOKEN: {secret}

good but i'm sure there is a way to load it without having to write it down!

**Comment by alligalli** [comment]
> 
> 
> > environment variables in an action file
> 
> env:
> SOCCER_CLI_API_TOKEN: {secret}
> 
> or
> 
> with:
> repo-token: ${{ secrets.GITHUB_TOKEN }}

immagine
maybe we should go for the "env" option, in our case SuperSecret should have another name

**Review by nikje27 — APPROVED** [review]

**Review by yauh-ask — APPROVED** [review]
hurray

**Pull request merged**
